// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkHE_LAdSvox46aHM_pNwfCtESGnVHC14',
    appId: '1:325084836791:web:a8173a0abc1492e42d6e32',
    messagingSenderId: '325084836791',
    projectId: 'anomolyolly',
    authDomain: 'anomolyolly.firebaseapp.com',
    storageBucket: 'anomolyolly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtyg5utLp7KhRtSYHEodvk1gja3ciQnqM',
    appId: '1:325084836791:android:ed8067c9b6488bbd2d6e32',
    messagingSenderId: '325084836791',
    projectId: 'anomolyolly',
    storageBucket: 'anomolyolly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzbQboYI9Zl4JFmTKQBfRUfYyB15AFX8',
    appId: '1:325084836791:ios:0bc8dbd1607d480f2d6e32',
    messagingSenderId: '325084836791',
    projectId: 'anomolyolly',
    storageBucket: 'anomolyolly.appspot.com',
    iosClientId: '325084836791-cgo5ubj29v97tuo7e89ac3mlknojdbva.apps.googleusercontent.com',
    iosBundleId: 'com.example.anomolyolly',
  );
}
